name: Metrics
on:
  schedule: [{cron: "0 */6 * * *"}]  # Run every 6 hours 
  workflow_dispatch:
  push:
    branches:
      - master
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: wangyuchen333
          template: classic
          base: header, activity, community, repositories, languages, metadata  # Add or remove as needed
          config_timezone: Asia/Shanghai  # Change timezone if necessary
